version: '3.8'

services:
  database:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: goddy
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: djangonautic-db
    ports:
      - "5432:5432"