import { useState,useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/App.module.css'

import Article from '@/components/Article';
import { getAllArticles } from '@/services/userService';


const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps() {
  const response = await getAllArticles()
  if (!response.data) return

  return {
    props: {
      articles: response.data
    }
  }

}

export default function Home({ articles }) {
  // const [hydrate, setHydrated] = useState(false)

  // useEffect(() => setHydrated(true), [])

  // if (!hydrate) return null
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <h1>Articles List</h1>
        <div className={styles.articles}>
          {articles.map((article, idx) => (
            <Article
              key={idx}
              article={article}
            />
          ))}
        </div>
      </>
    </>
  )
}
